///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a6d12ce4-e88c-4bf6-be02-0461f67437b8")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("a6d12ce4-e88c-4bf6-be02-0461f67437b8")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "a6d12ce4-e88c-4bf6-be02-0461f67437b8", ".\\RepositoryImages\\MyTestRepositorya6d12ce4.rximgres")
        {
            _rxmainframe = new MyTestRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a6d12ce4-e88c-4bf6-be02-0461f67437b8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("f70f3b0c-85ec-46ac-a51b-517999a494df")]
        public virtual MyTestRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("f70f3b0c-85ec-46ac-a51b-517999a494df")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            MyTestRepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;
            RepoItemInfo _rxtabstandardInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "f70f3b0c-85ec-46ac-a51b-517999a494df", "")
            {
                _rxtabintroduction = new MyTestRepositoryFolders.RxTabIntroductionFolder(this);
                _rxtabstandardInfo = new RepoItemInfo(this, "RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", "", 30000, null, "318cb2b4-7a5d-459a-83b4-526367d76577");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f70f3b0c-85ec-46ac-a51b-517999a494df")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f70f3b0c-85ec-46ac-a51b-517999a494df")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxTabStandard item.
            /// </summary>
            [RepositoryItem("318cb2b4-7a5d-459a-83b4-526367d76577")]
            public virtual Ranorex.TabPage RxTabStandard
            {
                get
                {
                    return _rxtabstandardInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The RxTabStandard item info.
            /// </summary>
            [RepositoryItemInfo("318cb2b4-7a5d-459a-83b4-526367d76577")]
            public virtual RepoItemInfo RxTabStandardInfo
            {
                get
                {
                    return _rxtabstandardInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("cb93b54e-51f6-493c-a66c-58b049d1fe92")]
            public virtual MyTestRepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("cb93b54e-51f6-493c-a66c-58b049d1fe92")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _rxstudiologoInfo;
            RepoItemInfo _lblwelcomemessageInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "cb93b54e-51f6-493c-a66c-58b049d1fe92", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/text[@accessiblename='Enter your name']", "", 30000, null, "3687c251-75c3-4c80-97e0-759d2ac11552");
                _rxstudiologoInfo = new RepoItemInfo(this, "RxStudioLogo", "picture[@controlname='RxStudioLogo']", "", 30000, null, "d363d245-7932-42ab-8925-d26233ebcdbb");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "text[@controlname='lblWelcomeMessage']", "", 30000, null, "97fa810e-e16f-404b-8d67-52021caa0d0b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cb93b54e-51f6-493c-a66c-58b049d1fe92")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cb93b54e-51f6-493c-a66c-58b049d1fe92")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("3687c251-75c3-4c80-97e0-759d2ac11552")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("3687c251-75c3-4c80-97e0-759d2ac11552")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The RxStudioLogo item.
            /// </summary>
            [RepositoryItem("d363d245-7932-42ab-8925-d26233ebcdbb")]
            public virtual Ranorex.Picture RxStudioLogo
            {
                get
                {
                    return _rxstudiologoInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The RxStudioLogo item info.
            /// </summary>
            [RepositoryItemInfo("d363d245-7932-42ab-8925-d26233ebcdbb")]
            public virtual RepoItemInfo RxStudioLogoInfo
            {
                get
                {
                    return _rxstudiologoInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("97fa810e-e16f-404b-8d67-52021caa0d0b")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("97fa810e-e16f-404b-8d67-52021caa0d0b")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
